services:
  - type: web
    name: badcopreview-server
    env: node
    plan: free
    buildCommand: "cd server && npm install"
    startCommand: "cd server && node index.js"
    envVars:
      - key: NODE_ENV
        value: production
    repo: https://github.com/maryofscot/badcopreview
    branch: main
    rootDir: server

  - type: web
    name: badcopreview-client
    env: static
    buildCommand: "cd client && npm install && npm run build"
    staticPublishPath: client/build
    repo: https://github.com/maryofscot/badcopreview
    branch: main
    rootDir: client
